[project]
name = "local-ai-help"
version = "0.1.0"
requires-python = ">=3.10,<3.13"
py-modules = ["main"]
dependencies = [
    "chromadb>=0.4.24",
    "langchain-core>=0.1.52,<0.2.0",
    "langchain-community>=0.0.38,<0.1.0",
    "langchain-text-splitters>=0.0.1",
]
